// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppRunnerHeartBeat app runner heart beat
//
// swagger:model app.RunnerHeartBeat
type AppRunnerHeartBeat struct {

	// alive time
	AliveTime TimeDuration `json:"alive_time,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// created by id
	CreatedByID string `json:"created_by_id,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// jobs in progress
	JobsInProgress int64 `json:"jobs_in_progress,omitempty"`

	// runner id
	RunnerID string `json:"runner_id,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this app runner heart beat
func (m *AppRunnerHeartBeat) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAliveTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppRunnerHeartBeat) validateAliveTime(formats strfmt.Registry) error {
	if swag.IsZero(m.AliveTime) { // not required
		return nil
	}

	if err := m.AliveTime.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("alive_time")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("alive_time")
		}
		return err
	}

	return nil
}

// ContextValidate validate this app runner heart beat based on the context it is used
func (m *AppRunnerHeartBeat) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAliveTime(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppRunnerHeartBeat) contextValidateAliveTime(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.AliveTime) { // not required
		return nil
	}

	if err := m.AliveTime.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("alive_time")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("alive_time")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppRunnerHeartBeat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppRunnerHeartBeat) UnmarshalBinary(b []byte) error {
	var res AppRunnerHeartBeat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
