// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComPowertoolsdevMonoPkgMetricsGauge github com powertoolsdev mono pkg metrics gauge
//
// swagger:model github_com_powertoolsdev_mono_pkg_metrics.Gauge
type GithubComPowertoolsdevMonoPkgMetricsGauge struct {

	// name
	Name string `json:"name,omitempty"`

	// tags
	Tags []string `json:"tags"`

	// value
	Value float64 `json:"value,omitempty"`
}

// Validate validates this github com powertoolsdev mono pkg metrics gauge
func (m *GithubComPowertoolsdevMonoPkgMetricsGauge) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com powertoolsdev mono pkg metrics gauge based on context it is used
func (m *GithubComPowertoolsdevMonoPkgMetricsGauge) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComPowertoolsdevMonoPkgMetricsGauge) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComPowertoolsdevMonoPkgMetricsGauge) UnmarshalBinary(b []byte) error {
	var res GithubComPowertoolsdevMonoPkgMetricsGauge
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
