// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ServiceCreateRunnerJobExecutionHeartBeatRequest service create runner job execution heart beat request
//
// swagger:model service.CreateRunnerJobExecutionHeartBeatRequest
type ServiceCreateRunnerJobExecutionHeartBeatRequest interface{}
