// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceGetInstallComponentPreviousConfigResponse service get install component previous config response
//
// swagger:model service.GetInstallComponentPreviousConfigResponse
type ServiceGetInstallComponentPreviousConfigResponse struct {

	// component config
	ComponentConfig *AppComponentConfigConnection `json:"componentConfig,omitempty"`
}

// Validate validates this service get install component previous config response
func (m *ServiceGetInstallComponentPreviousConfigResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateComponentConfig(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceGetInstallComponentPreviousConfigResponse) validateComponentConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.ComponentConfig) { // not required
		return nil
	}

	if m.ComponentConfig != nil {
		if err := m.ComponentConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("componentConfig")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("componentConfig")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this service get install component previous config response based on the context it is used
func (m *ServiceGetInstallComponentPreviousConfigResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateComponentConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceGetInstallComponentPreviousConfigResponse) contextValidateComponentConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.ComponentConfig != nil {

		if swag.IsZero(m.ComponentConfig) { // not required
			return nil
		}

		if err := m.ComponentConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("componentConfig")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("componentConfig")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ServiceGetInstallComponentPreviousConfigResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceGetInstallComponentPreviousConfigResponse) UnmarshalBinary(b []byte) error {
	var res ServiceGetInstallComponentPreviousConfigResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
