// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
)

// TimeDuration time duration
//
// swagger:model time.Duration


// ContextValidate validates this time duration based on context it is used
